### ISSUE TITLE
Implement :: Publish :: Increment Batch Version

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#251]
In GitLab by @kekefreedog on Dec 15, 2022, 16:36

> From Vincent Goy (221215)

## Need

- When a publish is made inside a batch, we have to increment the batch version

**Comment by ClementHector** [comment]
@louparis you can find out what they are waiting for, I don't understand.

**Comment by louparis** [comment]
I'm closing it after talking with Vincent
