### ISSUE TITLE
Template Builder do not put asset in hierarchy

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#277]
In GitLab by @support-bot on Jan 22, 2023, 21:05

> From Olivier Osotimehin

## Problem

When using the B**uild Workfile** **from template, the asset found are not in the expected hierarchy :**

![image](https://user-images.githubusercontent.com/70959083/236420459-1058ffca-a94a-4c27-9146-69d5723e1289.png)

this is the template :

![image](https://user-images.githubusercontent.com/70959083/236420483-761ed8d6-fe78-4469-8408-1b7b869b20af.png)

## How get error

Build a workfile from template in the shot 001\_0010 in the project TEST\_OP\_PUB in a lighting task

Fixes ynput/OpenPype#4854

**Comment by friquette** [comment]
The same issue was done by Toke Jepsen in a better way, here's his PR: https://github.com/ynput/OpenPype/pull/4854

**Comment by OlivierOsotimehin** [comment]
Tested on the latest 3.15.10-quad.2, on the shot 001_0010 TEST_OP2_PUB_23_7, the asset are not  all in the correct on hierarchy. 
Just the first one  : 

![image](https://github.com/quadproduction/OpenPype/assets/59604835/bf30199d-03c5-4e07-8460-e55a16f8ffd2)

**Comment by OlivierOsotimehin** [comment]
and when opening some task, for exemple 001_0020 layout on TEST_OP2_PUB_23_7 maya crashes 

`>>> [  Current context does not have any workfile yet.  ] 
>>> [  Launching "maya/2023" with args (1): ['/prod/softprod/apps/maya/2023.3/linux/bin/maya']  ] 
OpenPypeMongoConnection : INFO : Connected to mongodb://dockerquad:27027, delay 0.006s
openpype.pipeline.context_tools : INFO : Activating TEST_OP2_PUB_23_7..
MayaHost : INFO : /users_roaming/osotimehin/.local/share/openpype/3.15/openpype-v3.15.10-quad.2/openpype/hosts/maya/plugins/publish
MayaHost : INFO : Installing callbacks ... 
MayaHost : INFO : Installed event handler _on_scene_save..
MayaHost : INFO : Installed event handler _before_scene_save..
MayaHost : INFO : Installed event handler _on_after_save..
MayaHost : INFO : Installed event handler _on_scene_new..
MayaHost : INFO : Installed event handler _on_maya_initialized..
MayaHost : INFO : Installed event handler _on_scene_open..
MayaHost : INFO : Installed event handler _check_lock_file..
MayaHost : INFO : Installed event handler _before_close_maya..
openpype.pipeline.context_tools : INFO : Registering global plug-ins..
openpype.pipeline.context_tools : INFO : Registering root: {'work': /prod/project}
Starting OpenPype usersetup...
Finished OpenPype usersetup.
Warning: Setting a new default format with a different version or profile after the global shared context is created may cause issues with context sharing.
Initialized VP2.0 renderer {
  Version : 2016.11.62.12. Feature Level 5.
  Adapter : Quadro RTX 5000/PCIe/SSE2
  Vendor ID: 4318. Device ID : 
  Driver : 4.6.0 NVIDIA 530.30.02.
  API : OpenGL V.4.6.
  Max texture size : 16384 * 16384.
  Max texture coords : 32
  Shader versions supported (Vertex: 5, Geometry: 5, Pixel 5).
  Shader compiler profile : (Best card profile)
  Active stereo support available : 0
  GPU Memory Limit : 16384 MB.
  CPU Memory Limit : 121948 MB.
  MultiDraw consolidation : enabled
}
OpenCL evaluator is attempting to initialize OpenCL.
Detected 1 OpenCL Platforms: 
 0: NVIDIA Corporation. NVIDIA CUDA. OpenCL 3.0 CUDA 12.1.68.
 Supported extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_khr_gl_event cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_nv_kernel_attribute cl_khr_device_uuid cl_khr_pci_bus_info cl_khr_external_semaphore cl_khr_external_memory cl_khr_external_semaphore_opaque_fd cl_khr_external_memory_opaque_fd 
 Selected matching OpenCL Platform: NVIDIA Corporation NVIDIA CUDA OpenCL 3.0 CUDA 12.1.68.
OpenCL evaluator choosing OpenCL platform NVIDIA Corporation.
Choosing OpenCL Device Quadro RTX 5000.  Device Type: GPU  Device is available.

Stack trace:
  TdnRenderLayerManager::findLayerCnt() const
  TdnRenderLayerManager::current()
  TsceneOperator::saveScene(Tstring&, TsceneFile*, bool, bool)
  TfileCmd::handleFileSaveFlag(TargDatabase&, TsceneFile*)
  TfileCmd::handleFlags(TargDatabase&, TsceneFile*, TnamespaceSwapper*, TgraphDiff*)
  TfileCmd::handleFlags(TargDatabase&, Tstring const&)
  TfileCmd::doCommand(TargList&)
  TpythonInterpreter::dispatchMayaCommand(TmetaCommand&, _object*, _object*)
  pythonDispatchMayaCommand(TmetaCommand&, _object*, _object*)
  /prod/softprod/apps/maya/2023.3/linux/lib/libShared.so(+0x6f4a47) [0x1461c67d8a47]
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0xfa273) [0x1461b4b2f273]
  _PyObject_MakeTpCall
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x65bbb) [0x1461b4a9abbb]
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x19cd84) [0x1461b4bd1d84]
  _PyFunction_Vectorcall
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x65bbb) [0x1461b4a9abbb]
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x65bbb) [0x1461b4a9abbb]
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x19cd84) [0x1461b4bd1d84]
  _PyFunction_Vectorcall
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x19cd84) [0x1461b4bd1d84]
  _PyFunction_Vectorcall
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x65bbb) [0x1461b4a9abbb]
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x65bbb) [0x1461b4a9abbb]
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x65bbb) [0x1461b4a9abbb]
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x65bbb) [0x1461b4a9abbb]
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x65bbb) [0x1461b4a9abbb]
  _PyEval_EvalFrameDefault
  /prod/softprod/apps/maya/2023.3/linux/lib/libpython3.9.so.1.0(+0x65bbb) [0x1461b4a9abbb]
  _PyEval_EvalFrameDefault
1Writing crash report in /usr/tmp/untitled[Recovered-osotimehin.2023-06-06-11.07].crash
/prod/softprod/apps/maya/2023.3/linux/bin/maya: line 203: 3081102 Segmentation fault      (core dumped) /prod/softprod/apps/maya/2023.3/linux/bin/maya.bin

`

**Comment by tokejepsen** [comment]
Should be resolved by #4854 now.
