### ISSUE TITLE
Template Builder does not apply Look on found asset Maya

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#280]
In GitLab by @support-bot on Jan 23, 2023, 11:06

> From Olivier Osotimehin

## Problem

In maya

When i build a Lighting template, i want to find and reference **animation** from **linked Asset** and then applying look on them.

I do that by adding a place holder, with(look, json, changing the order to 1 ) :

![image](https://user-images.githubusercontent.com/70959083/236424446-c67c73a2-d1c1-43de-af53-9520c8154fce.png)

## How get error

Build Lighting scene (001\_0010 on TEST\_OP\_PUB)

What is funny is that the locator of the look placeholder disapear after the scene is build:

![image](https://user-images.githubusercontent.com/70959083/236424518-ed486ddb-368b-4e13-9fbf-273472e41489.png)

**Comment by OlivierOsotimehin** [comment]
duplicate
