### ISSUE TITLE
Fix Studio :: OpenPype :: Easier Menu in "Create Place Holder" tool

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#297]
In GitLab by @support-bot on Jan 29, 2023, 14:27

> From Olivier Osotimehin

## Need

For now, when creating template in Maya/Nuke with the Create Place Holder menu, we have to know by heart the exact name of the family, the representation.

We also have to know the correct loader to use.

It would be far easier to :

- Have a drop down menu for all the entries like family, representation (like there is in the Loader menu )
- The loader menu can be auto filtered to show only the loader compatible with the chosen representation
- have help on the different Arguments available and what they do

![d67781dc62](https://my-gitlab-bucket.s3.amazonaws.com/602095763/142846afb5fec73da6cd2b77b05bc2274bacee170fad04cd77933bb07782c429/d67781dc62.png)

## 

## Softwares concerned

OpenPYPE, Openpype

**Comment by friquette** [comment]
Have a drop-down menu listing all families

**Comment by friquette** [comment]
Have a drop-down menu listing all representations

**Comment by ClementHector** [comment]
I'm closing this one, don't forget to put the labels on the new issues otherwise we don't see it in the project.
