### ISSUE TITLE
Look publish stuck at Extract Look on OP 3.15.1

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#320]
In GitLab by @support-bot on Feb 23, 2023, 16:15

> asset cow task surfacing on **TEST\_OP\_PUB,** publish look

> the publish never finish

![image](https://user-images.githubusercontent.com/70959083/236420822-9ddaf629-ceb8-4976-83ce-21a1473f5cc1.png)

## Softwares concerned

Maya, Fix

**Comment by ClementHector** [comment]
@kekefreedog I can't check on the ws213 can you try?

**Comment by ClementHector** [comment]
Solve with the last rocky linux install.

**Comment by OlivierOsotimehin** [comment]
so to test we must have that last install ?

**Comment by ClementHector** [comment]
Yes I tried on the @kekefreedog  workstation.

**Comment by OlivierOsotimehin** [comment]
I tested it on my workstation with the last packages add IT team and it didn"t work. We have to test it on an asset with texture

**Comment by ClementHector** [comment]
I'll come Monday to check with you.

**Comment by ClementHector** [comment]
it's due to a missing library in rocky linux, it freezes maketx. @fixstudio-it

**Comment by ClementHector** [comment]
The `maketx -h` command works on Rocky8, I will change the code for that.

**Comment by ClementHector** [comment]
@OlivierOsotimehin It should work on your computer.

**Comment by ClementHector** [comment]
Can you try the maketx command in a terminal and give me the log.

**Comment by OlivierOsotimehin** [comment]
maketx
bash: maketx: command not found

**Comment by ClementHector** [comment]
Solve with the compile OIIO from @fixstudio-it which are stored in /home/linuxbrew/.linuxbrew/bin

**Comment by OlivierOsotimehin** [comment]
it works in centos&rocky with the same OIIO. Thanks everyone !
