### ISSUE TITLE
Action for create default objects on new Ftrack project

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#331]
In GitLab by @support-bot on Mar 3, 2023, 17:06

> From 3D (230303)

## Need

We would like to add action in Ftrack project to create defaults objects in current project.

Here the 4 defaults objects we would like to create :

![image](https://user-images.githubusercontent.com/70959083/236421253-514e8656-5fd2-47f3-96bc-1a26257becbf.png)

Then it could be nice to be able to modify it via OpenPype Settings.

> Please notice that **Name** &amp; **Type** is very important !!!

## Resources

https://fixstudio.ftrackapp.com/#entityId=acb580f4-bf93-4a84-b10c-e14e8e666947&amp;entityType=show&amp;itemId=projects&amp;view=tasks

## Softwares concerned

Ftrack, Fix

**Comment by OlivierOsotimehin** [comment]
This is a way to have "ftrack template" project. It should be possible to choose between several premade hierarchy i guess. 
fe : to create a hierarchy for
- commercials  
- fiction series with episodes 
- feature film 

But the best way to do that would be with the project creator, and if we choose ftrack project we choose a project template already set with the correct particularities 
To be discuss what's the best way of doing things 
One is faster than the other ... but can bring more confusion

**Comment by ClementHector** [comment]
Could a button in ftrack fulfill this need?

**Comment by OlivierOsotimehin** [comment]
There is one major thing that seams to be difficult to change After project création : 
It the project 'Schema' (all the type of task used, status and so on ) 


https://forum.ftrack.com/topic/376-change-schema/

We should be able to create a project by choosing the project schéma (which would drive thé kind of hierarchy we want inside it) 

But if a buttons fullfill this need it s good

**Comment by mre7a** [comment]
The project structure will be created on the server and also in Ftrack using the Create Project Structure action.

**Comment by OlivierOsotimehin** [comment]
We just need Ftrack objects so that it' doesn't interfere with server strucure

**Comment by mre7a** [comment]
I renamed the branch, so the new one is here : 

https://github.com/quadproduction/OpenPype/tree/enhancement/331-action-for-create-default-objects-on-new-ftrack-project

I put this here because it is not possible to unlink the old branch and link the new one to the issue.

**Comment by ClementHector** [comment]
![image](https://github.com/quadproduction/OpenPype/assets/7068597/541aae0a-a49c-4e43-99b5-97a1adcb5f35)
![image](https://github.com/quadproduction/OpenPype/assets/7068597/b95ad736-6f96-434b-bfd6-f181ca751af5)

**Comment by mre7a** [comment]
To test the code:

- checkout to the branch
- launch openpype
- refresh ftrack on web interface
- you should see a new action for the projects "**Create Ftrack Project Structure**"
- it gets the project hierarchy from `Openpype project settings - Gloal - Project Folder Structure`. 
- you can test it on an empty project, you should verify that it create the folders on ftrack (the ones that have a `[ftrack]` in their names) and not on the server. 

P.S. I think you can test it on the Vortex project.

**Comment by ClementHector** [comment]
Test on project MISKINA with success.

**Comment by louparis** [comment]
It works but may be improved later - let's discuss it Olivier
