### ISSUE TITLE
Disable 'persp' camera on Build workfile from template

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#336]
In GitLab by @support-bot on Mar 7, 2023, 08:14

When we build an asset workfile with build workfile from template, we load our turntable camera.

But then we have 2 renderables camera : **persp** and turntable **mayaSceneMain\_01\_:cam**

To render the turntable we know that we will **always** have to disable the persp camera so we would like it disable and at the build of the workfile.

Maybe a way to be more generic would be to have a maya python script available to us (in Openpype Settings)so that we could do several custom command specific to each task.
![image](https://user-images.githubusercontent.com/70959083/236420582-5e517c6f-3cbe-4117-a898-35e92fedc3f9.png)

## Softwares concerned

Maya, Fix

**Comment by mre7a** [comment]
Merge request 
https://github.com/ynput/OpenPype/pull/4815

**Comment by OlivierOsotimehin** [comment]
This is working, tested in several context, asset / shot, it's good

**Comment by louparis** [comment]
A new ticket was opened for this specific issue : https://github.com/quadproduction/OpenPype/issues/421
