### ISSUE TITLE
Reference is broken/imported when scene is build from template

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#341]
In GitLab by @support-bot on Mar 8, 2023, 14:50

> From...

In our asset template, we load with Openpype loader as a reference a turntable asset :

![image](https://user-images.githubusercontent.com/70959083/236420368-ce3e43a3-19dd-44d0-8308-8b750bd2fc6a.png)

but when we build a scene with template, the reference is imported and broken and maya complain :

**// Error: file: /prod/softprod/apps/maya/2023.3/linux/scripts/AETemplates/AEtransformRelated.mel line 58: Reference node 'turntable\_mayaSceneMain\_01\_RN' is not associated with a reference file.**

the turntable is imported and no longer a reference :

![image](https://user-images.githubusercontent.com/70959083/236420387-7c32e0b8-500d-442c-b989-cbe3ba0c68e9.png)

## Softwares concerned

Maya, Fix

**Comment by mre7a** [comment]
Merge request 
https://github.com/ynput/OpenPype/pull/4797

**Comment by ClementHector** [comment]
> Merge request [ynput#4797](https://github.com/ynput/OpenPype/pull/4797)

There is one suggestion left. 
Always put the long name for the maya arguments, it's easier to read the code.

**Comment by OlivierOsotimehin** [comment]
this is working
