### ISSUE TITLE
Display handle is ticked, and should not

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#342]
In GitLab by @support-bot on Mar 8, 2023, 14:58

> From...

When we load/reference an asset from openpype loader display handle is ticked and prevent to select correctly in the viewport object

exemple load the **can** asset in a new scene (project TEST\_OP2\_PUB\_23\_7)

![f55334920b](https://my-gitlab-bucket.s3.amazonaws.com/602095763/5bd1370a5d7fb8db2527f86b48fb2731e5bf166d25ab48f601977f4daaf0f31c/f55334920b.png)

## Softwares concerned

Maya, Fix

**Comment by mre7a** [comment]
Pull request successfully merged and closed :)

**Comment by ClementHector** [comment]
Please add your spend time.

**Comment by OlivierOsotimehin** [comment]
this is working
