### ISSUE TITLE
Update frame range of scene doesn't update frame range in animation instance

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#345]
In GitLab by @support-bot on Mar 9, 2023, 16:02

> From...

## Udpate frame range of scene doesn't update frame range in animation instance

in scene project TEST\_OP2\_PUB\_23\_7

shot 001\_0010

![image](https://user-images.githubusercontent.com/70959083/236421071-6fe5d3c3-647e-4f50-8f92-f3c6e5569430.png)

## Softwares concerned

Maya, Fix

**Comment by louparis** [comment]
New PR for this : https://github.com/ynput/OpenPype/pull/5201
