### ISSUE TITLE
Animation instance doesn't have the right subset name when created with Template Builder

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#346]
In GitLab by @support-bot on Mar 9, 2023, 16:07

> the subset is call feadingPump\_rigMain\_01\_

> and should be call feadingPump\_animationMain\_01

![image](https://user-images.githubusercontent.com/70959083/236421186-9b2eb215-2fb2-4443-96b3-b658e3cd1508.png)

## Softwares concerned

Maya, Fix

**Comment by mre7a** [comment]
Merge request 
https://github.com/ynput/OpenPype/pull/4877

**Comment by ClementHector** [comment]
@mre7a 

> Merge request [ynput#4877](https://github.com/ynput/OpenPype/pull/4877)

I thought bigroy solved this in another PR?

**Comment by mre7a** [comment]
I don't think so, do you have the link of the PR ?
His suggestion in the comments is useful, but does not solve our problem. 

I have just asked him why there are no answers.

**Comment by mre7a** [comment]
If you want to test it, I added some documentation here:
https://openpype.io/docs/admin_hosts_maya#templated-build-workfile
