### ISSUE TITLE
Slow interface in Nuke

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#361]
In GitLab by @support-bot on Mar 21, 2023, 11:15

> local user

## Problem

Nuke is extremely slow when opened through pype - any file knob takes forever to open, and after a while, software comes to a complete standstill and it's not possible to navigate in the software and I have to kill the process.

## How get error

- Open Nuke through Pype

- Work for a while

## Log

no message in console

## Softwares concerned

Nuke, Wizz

**Comment by louparis** [comment]
Nuke works well on linux 3.15, fluid 
Tested on windows OP3.14 : everything is laggy - should be corrected once 3.15 is deployed ?

**Comment by louparis** [comment]
Looks like it works on 3.15. It's still slower than linux (may be accentuated by nomachine)

**Comment by hfarre** [comment]
Do you have any precise exemple scene ?  
With an empty nuke, the oppening throught openpype is not slow, and regular I would say

**Comment by louparis** [comment]
From what we tested with Guillaume last time, loading elements (without using openpype, but having it open) using "read" would make everything lag/stop in Nuke. But in general, opening any scene would make everything very slow

**Comment by hfarre** [comment]
Tested on 3.15.12, with nuke 13.2 on the following shot:


![Image](https://github.com/quadproduction/OpenPype/assets/139864808/e55a2824-1a4c-4ea5-a198-0b7dc031b054)


After importing a few read, with and without openpye, I didn't have any lag

I sugguest  we keep an eye on this on the future project and see if it lag once more or not later
