### ISSUE TITLE
OpenPype is Storing files where it shoud'nt

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#363]
In GitLab by @support-bot on Mar 23, 2023, 14:09

> From WIZZ Production

## Problem

The pipeline is storing files in wrong folders with wrong names :

![image](https://user-images.githubusercontent.com/70959083/236422485-fc3f3f70-896a-418f-96c9-70b89ee34416.png)

The Rough Animation Work Folder doesn't exist but when we publish the Styleframes it creates a Rough animation folder on the Publish File.

## Softwares concerned

TvPaint, Wizz

**Comment by ClementHector** [comment]
Video from Rebeca => https://drive.google.com/file/d/1FwacZYT1JFg8gOyKBIq_EHfY2-0YZQQY/view

**Comment by ClementHector** [comment]
I think that choosing a context different and doing copy and open should work, it’s clearly a bug. This may be fixed because wizz is working on an older version.
I propose that we first reproduce the problem on the version that is used by wizz, then we try on the last version. To see if it’s fixed!

**Comment by louparis** [comment]
Tested by both @friquette and I, the choosing diff context now works on latest versions of OP.
