### ISSUE TITLE
Nuke Survival Toolkit

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#370]
In GitLab by @support-bot on Mar 31, 2023, 09:38

> From Thibault Martegani

## Need

✅ We don't want to load in Guizmo side bar the **Nuke Survival Toolkit** at Nuke startup.

However, when we do an "update" in the Tab Menu, we would like to load them in the Tab Menu

## Resources

![image](https://my-gitlab-bucket.s3.amazonaws.com/602095763/0e22fcf929de22161034d068f82826fe5f7b53bb38da1200086efaf0525f6e03/Peek_2023-03-31_11-35.gif)

## Softwares concerned

Nuke, Fix

**Comment by SherineKB** [comment]
More details : 

What is needed ? 

- Tab and search for "update all plugins" to import **all** the existing plugins (old versions, none usually used ones...). 
( _This option is already available when you load a project from Ftrack. We need it for when it's loaded from Openpype_)

**Comment by ClementHector** [comment]
> * ( _This option is already available when you load a project from Ftrack. We need it for when it's loaded from Openpype_)

The good way is to load from ftrack, the load in OpenPype will be removed soon.
