### ISSUE TITLE
Update Nuke render name with OCIO color space

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#371]
In GitLab by @support-bot on Mar 31, 2023, 10:32

> From Thibault Martegani

## Need

We would like to update the name of the render to that :

- 078\_0100\_comp\_scene\_ACEScg\_main\_v002.0091.exr
- \[shot\_name\]\_\[task\]\_\[colorspace\]\_\[variant\]\_\[version\].\[frame\].\[ext\]

## Softwares concerned

Nuke, Fix

**Comment by kekefreedog** [comment]
Hello,

I update Anatomy > Templates > Render > File in OpenPype settings

Before : ~~`{asset}_{subset}_{@version}<_{output}><.{@frame}>.{ext}`~~

After : `{asset}_{task[short]}_{subset}_ACEScg_{@version}<_{output}><.{@frame}>.{ext}`

> I kept the subset token

I tried a render in Nuke, now we got this : 

![image](https://github.com/quadproduction/OpenPype/assets/70959083/b68bef8b-a276-4fd2-9cbe-4ad89cecff55)
