### ISSUE TITLE
Auto Backdrop :: Set cursor on "text" field

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#374]
In GitLab by @support-bot on Mar 31, 2023, 16:22

> From Thibault Martegani

## Need

Using Auto Backdrop, when we press alt + B on nodes, it create a backdrop.

We would like to set the cursor directly on "Text" field - when auto backdrop is created - to be able to quickly write the name into the backdrop.

![image](https://user-images.githubusercontent.com/70959083/236422882-cb917c04-4a67-4eab-b8a8-66d5fcc19cf2.png)

## Softwares concerned

Nuke, Fix

**Comment by ccaillot** [comment]
As I don't have a full access of Nuke's Qt wrapper with python, I've added a Panel where you can enter the backdrop's text and press enter in order to avoid the go & back with the mouse

**Comment by ClementHector** [comment]
@ccaillot For the new time, move the issue to the `quad-module` repository and then create a branch and a PR on this repository.
TODO: create CICD on `quad-module` to deploy on PR

**Comment by kekefreedog** [comment]
It works for me !! I close the issue, thank you @ccaillot :D
