### ISSUE TITLE
Settings in OpenPype Prod 3.15.3 not applied

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#384]
In GitLab by @support-bot on Apr 17, 2023, 10:39

> From Kevin Zarshenas &amp; Marc Gutmann

## Problem

We observe settings are not apply in OpenPype Prod 3.15.3 : When we modify a settings in OpenPype Prod 3.15.3, we open softwares like Maya &amp; Hiero... and then we have default settings uses on it.

## How get error

1. Open setting in OpenPype &gt; Admin &gt; Studio Settings &gt; Projects &gt; TEST\_OP2\_PUB\_23\_7
2. Try to change a setting :
   - Exemple : Change "Main" To "Basic" in Maya Settings
   - Exemple : Change *Clip Name Template* in Hiero Settings
3. Open a soft like Hiero &amp; Maya
4. Check is the settings is well applied

## Ressources

![image](https://user-images.githubusercontent.com/70959083/236423618-9f77657d-dd92-4d57-9c7f-b0a63a7a7a74.png)

## Softwares concerned

Maya, Fix

**Comment by kekefreedog** [comment]
Hello @ccaillot ! Je viens de faire un test dans OpenPype 3.15.9-nightly.1 et toujours le même souci : 

![image](https://github.com/quadproduction/OpenPype/assets/70959083/35972f61-b205-4fb4-8a99-b0ae34af306b)

Dans les settings OpenPype > Clip Name Template j'ai mis : `{family}/{asset}_{task[name]}_{subset}_{version}`

Quand je load un *render* je devrais avoir un clip nommé et dans les dossier comme ça : `Loader/renderShots/001/001_0010/001_0010_compositing_renderCompMain_v002`

Or j'obtiens actuellement un résultat qui correspond à celui du template par défaut `Loader/Shots/001/001_0010/001_0010_renderCompoMain_exr` qui corredpond au template suivant : `{asset}_{subset}_{representation}`

**Comment by ccaillot** [comment]
The problem has been transmitted to Ynput, and a PR has been created by them (https://github.com/ynput/OpenPype/pull/5073)
The issue will be resolved once Ynput will push the PR
