### ISSUE TITLE
Set Framerange doesn't apply after Template Builder used

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#386]
In GitLab by @support-bot on Apr 17, 2023, 15:19

> From Marc Gutmann

## Problem

When we create a maya scene using Template Builder, then "set framerange" doesn't work for FPS.

## How get error

- Open Maya scene, use template builder
- Change FPS in Ftrack
- On Maya click on OpenPype &gt; Set Framerange
- FPS isn't update in the Maya scene

## Softwares concerned

Maya, Ftrack, Fix

**Comment by OlivierOsotimehin** [comment]
this now works

**Comment by louparis** [comment]
Can we close the ticket if it's all good ?

**Comment by OlivierOsotimehin** [comment]
yes
