### ISSUE TITLE
Include / Exclude Handles

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#387]
In GitLab by @support-bot on Apr 17, 2023, 15:23

> From Marc Gutmann

## Problem

In OpenPype settings &gt; Projects &gt; TEST\_OP2\_PUB &gt; Maya &gt; Incluse / Exclude Handles , we can define globaly or by tasks if we want use or not handles in workfiles

When we unchecked "By default", then we enable handles for "animation", then those values are not apply on maya publish instance, nor review.

## Softwares concerned

Maya, Fix

**Comment by mre7a** [comment]
Blocked. We should wait for this PR, which could solve the problem. 

https://github.com/ynput/OpenPype/pull/4793

**Comment by mre7a** [comment]
Linked ticket : #345

**Comment by louparis** [comment]
last linked pr : https://github.com/ynput/OpenPype/pull/5201
