### ISSUE TITLE
Dev User for Fix Project Creator

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#388]
In GitLab by @support-bot on Apr 17, 2023, 16:25

> From Kevin Zarshenas

## Need

We created a new user dev@fixstudio.com for all dev api needed.

- Login : `dev@fixstudio.com`
- Password : > `Le mot de passe habituel` ;)

Can you use this account for the Fix Project Creator ?

## Software concerned

Fix

**Comment by kekefreedog** [comment]
Il faut se connecter au comptes Dev et généré une nouvelle key !

**Comment by kekefreedog** [comment]
![image](https://user-images.githubusercontent.com/70959083/236424355-36b606ae-d148-4d86-b0d3-6e7a1a515751.png)
