### ISSUE TITLE
Define the publications sets (camera, assets, review) with the frame in / frame out and handles from Ftrack when we build the first scene

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#389]
In GitLab by @support-bot on Apr 17, 2023, 16:26

> From Marc Gutmann

## Problem

When we build the first scene, define the publications sets (camera, assets, review) with the frame in / frame out and handles from Ftrack.

Today, publication sets have template information.

## How get error

Build the first scene in animation department (TEST\_OP2\_PUB\_23\_7 - shot 001\_0010)

![image](https://user-images.githubusercontent.com/70959083/236420678-6526770d-8a6b-474c-bd10-6f0bd764e392.png)

## Softwares concerned

Maya, Ftrack, Fix

**Comment by friquette** [comment]
PR: https://github.com/ynput/OpenPype/pull/4996

**Comment by louparis** [comment]
New PR for this : https://github.com/ynput/OpenPype/pull/5201
