### ISSUE TITLE
Rendering issue with Deadline

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#390]
In GitLab by @support-bot on Apr 18, 2023, 13:11

> From... Marc

## Problem

I'm testing rendering with Maya / OpenPype and I have a problem with Deadline

## How get error

![deadline_issue_from_gitlab](https://github.com/quadproduction/OpenPype/assets/68907585/0c0532db-5654-4c41-ba22-4b055848bc41)

Path :

/prod/prod2/Projets/2023/TEST\_OP2\_PUB\_23\_7/5\_FILM/Assets/cube/work/model/cube\_model\_v003.ma

## Log

<pre class="ql-syntax">﻿<span class="hljs-string">=======================================================</span>

<span class="hljs-string">Error</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-attr">Error:</span> <span class="hljs-string">Global</span> <span class="hljs-string">job</span> <span class="hljs-string">preload</span> <span class="hljs-string">script</span> <span class="hljs-string">'/tmp/deadline/ws232/plugins/643e94b79c6c6405f2284e58/GlobalJobPreLoad.py':</span> <span class="hljs-attr">RuntimeError :</span> <span class="hljs-string">Cannot</span> <span class="hljs-string">find</span> <span class="hljs-string">compatible</span> <span class="hljs-string">version</span> <span class="hljs-string">available</span> <span class="hljs-string">for</span> <span class="hljs-string">version</span> <span class="hljs-number">3.15.4</span> <span class="hljs-string">requested</span> <span class="hljs-string">by</span> <span class="hljs-string">the</span> <span class="hljs-string">job.</span> <span class="hljs-string">Please</span> <span class="hljs-string">add</span> <span class="hljs-string">it</span> <span class="hljs-string">through</span> <span class="hljs-string">plugin</span> <span class="hljs-string">configuration</span> <span class="hljs-string">in</span> <span class="hljs-string">Deadline</span> <span class="hljs-string">or</span> <span class="hljs-string">install</span> <span class="hljs-string">it</span> <span class="hljs-string">to</span> <span class="hljs-string">configured</span> <span class="hljs-string">directory.</span> <span class="hljs-string">(FranticX.Scripting.PythonNetException)</span>

  <span class="hljs-string">File</span> <span class="hljs-string">"/tmp/deadline/ws232/plugins/643e94b79c6c6405f2284e58/GlobalJobPreLoad.py",</span> <span class="hljs-string">line</span> <span class="hljs-number">434</span><span class="hljs-string">,</span> <span class="hljs-string">in</span> <span class="hljs-string">__main__</span>

    <span class="hljs-string">inject_openpype_environment(deadlinePlugin)</span>

  <span class="hljs-string">File</span> <span class="hljs-string">"/tmp/deadline/ws232/plugins/643e94b79c6c6405f2284e58/GlobalJobPreLoad.py",</span> <span class="hljs-string">line</span> <span class="hljs-number">309</span><span class="hljs-string">,</span> <span class="hljs-string">in</span> <span class="hljs-string">inject_openpype_environment</span>

    <span class="hljs-string">).format(requested_version))</span>

   <span class="hljs-string">at</span> <span class="hljs-string">Python.Runtime.PyObject.Invoke(PyObject[]</span> <span class="hljs-string">args)</span>

   <span class="hljs-string">at</span> <span class="hljs-string">Python.Runtime.PyObject.InvokeMethod(String</span> <span class="hljs-string">name,</span> <span class="hljs-string">PyObject[]</span> <span class="hljs-string">args)</span>

   <span class="hljs-string">at</span> <span class="hljs-string">FranticX.Scripting.PythonNetScriptEngine.CallFunction(String</span> <span class="hljs-string">moduleName,</span> <span class="hljs-string">String</span> <span class="hljs-string">functionName,</span> <span class="hljs-string">Object[]</span> <span class="hljs-string">args)</span>

   <span class="hljs-string">at</span> <span class="hljs-string">Deadline.Plugins.PluginWrapper.d()</span>

   <span class="hljs-string">at</span> <span class="hljs-string">Deadline.Plugins.PluginWrapper.StartJob(String&</span> <span class="hljs-string">outMessage,</span> <span class="hljs-string">AbortLevel&</span> <span class="hljs-string">abortLevel)</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-string">Type</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-string">RenderPluginException</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-string">Stack</span> <span class="hljs-string">Trace</span>

<span class="hljs-string">=======================================================</span>

   <span class="hljs-string">at</span> <span class="hljs-string">Deadline.Plugins.SandboxedPlugin.d(DeadlineMessage</span> <span class="hljs-string">bgm,</span> <span class="hljs-string">CancellationToken</span> <span class="hljs-string">bgn)</span>

   <span class="hljs-string">at</span> <span class="hljs-string">Deadline.Plugins.SandboxedPlugin.StartJob(Job</span> <span class="hljs-string">job,</span> <span class="hljs-string">CancellationToken</span> <span class="hljs-string">cancellationToken)</span>

   <span class="hljs-string">at</span> <span class="hljs-string">Deadline.Slaves.SlaveRenderThread.c(TaskLogWriter</span> <span class="hljs-string">ajt,</span> <span class="hljs-string">CancellationToken</span> <span class="hljs-string">aju)</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-string">Log</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-attr">2023-04-18 15:02:37:  0:</span> <span class="hljs-string">Loading</span> <span class="hljs-string">Job's</span> <span class="hljs-string">Plugin</span> <span class="hljs-string">timeout</span> <span class="hljs-string">is</span> <span class="hljs-string">Disabled</span>

<span class="hljs-attr">2023-04-18 15:02:37:  0: SandboxedPlugin:</span> <span class="hljs-string">Render</span> <span class="hljs-string">Job</span> <span class="hljs-string">As</span> <span class="hljs-string">User</span> <span class="hljs-string">enabled,</span> <span class="hljs-string">running</span> <span class="hljs-string">as</span> <span class="hljs-string">user</span> <span class="hljs-string">'mgutmann',</span> <span class="hljs-string">which</span> <span class="hljs-string">is</span> <span class="hljs-string">defined</span> <span class="hljs-string">in</span> <span class="hljs-string">the</span> <span class="hljs-string">User</span> <span class="hljs-string">Settings</span> <span class="hljs-string">for</span> <span class="hljs-string">this</span> <span class="hljs-string">job's</span> <span class="hljs-string">user</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0:</span> <span class="hljs-string">Failed</span> <span class="hljs-string">to</span> <span class="hljs-string">properly</span> <span class="hljs-string">create</span> <span class="hljs-string">Deadline</span> <span class="hljs-string">logs</span> <span class="hljs-string">folder</span> <span class="hljs-string">'/var/log/Thinkbox/Deadline10'</span> <span class="hljs-attr">because:</span> <span class="hljs-string">Access</span> <span class="hljs-string">to</span> <span class="hljs-string">the</span> <span class="hljs-string">path</span> <span class="hljs-string">'/var/log/Thinkbox/Deadline10'</span> <span class="hljs-string">is</span> <span class="hljs-string">denied.</span> <span class="hljs-string">(System.UnauthorizedAccessException)</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0:</span> <span class="hljs-string">Executing</span> <span class="hljs-string">plugin</span> <span class="hljs-string">command</span> <span class="hljs-string">of</span> <span class="hljs-string">type</span> <span class="hljs-string">'Initialize Plugin'</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO:</span> <span class="hljs-string">Executing</span> <span class="hljs-string">plugin</span> <span class="hljs-string">script</span> <span class="hljs-string">'/tmp/deadline/ws232/plugins/643e94b79c6c6405f2284e58/MayaBatch.py'</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO:</span> <span class="hljs-string">Plugin</span> <span class="hljs-string">execution</span> <span class="hljs-string">sandbox</span> <span class="hljs-string">using</span> <span class="hljs-string">Python</span> <span class="hljs-string">version</span> <span class="hljs-number">3</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO: About:</span> <span class="hljs-string">Maya</span> <span class="hljs-string">Batch</span> <span class="hljs-string">Plugin</span> <span class="hljs-string">for</span> <span class="hljs-string">Deadline</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO:</span> <span class="hljs-string">The</span> <span class="hljs-string">job's</span> <span class="hljs-string">environment</span> <span class="hljs-string">will</span> <span class="hljs-string">be</span> <span class="hljs-string">merged</span> <span class="hljs-string">with</span> <span class="hljs-string">the</span> <span class="hljs-string">current</span> <span class="hljs-string">environment</span> <span class="hljs-string">before</span> <span class="hljs-string">rendering</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0:</span> <span class="hljs-string">Done</span> <span class="hljs-string">executing</span> <span class="hljs-string">plugin</span> <span class="hljs-string">command</span> <span class="hljs-string">of</span> <span class="hljs-string">type</span> <span class="hljs-string">'Initialize Plugin'</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0:</span> <span class="hljs-string">Start</span> <span class="hljs-string">Job</span> <span class="hljs-string">timeout</span> <span class="hljs-string">is</span> <span class="hljs-string">disabled.</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0:</span> <span class="hljs-string">Task</span> <span class="hljs-string">timeout</span> <span class="hljs-string">is</span> <span class="hljs-string">disabled.</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: Loaded job:</span> <span class="hljs-string">cube_model_v003.ma</span> <span class="hljs-bullet">-</span> <span class="hljs-string">Turntable1</span> <span class="hljs-string">(643e94b79c6c6405f2284e58)</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0:</span> <span class="hljs-string">Executing</span> <span class="hljs-string">plugin</span> <span class="hljs-string">command</span> <span class="hljs-string">of</span> <span class="hljs-string">type</span> <span class="hljs-string">'Start Job'</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: DEBUG:</span> <span class="hljs-string">S3BackedCache</span> <span class="hljs-string">Client</span> <span class="hljs-string">is</span> <span class="hljs-string">not</span> <span class="hljs-string">installed.</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO:</span> <span class="hljs-string">Executing</span> <span class="hljs-string">global</span> <span class="hljs-string">asset</span> <span class="hljs-string">transfer</span> <span class="hljs-string">preload</span> <span class="hljs-string">script</span> <span class="hljs-string">'/tmp/deadline/ws232/plugins/643e94b79c6c6405f2284e58/GlobalAssetTransferPreLoad.py'</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO:</span> <span class="hljs-string">Looking</span> <span class="hljs-string">for</span> <span class="hljs-string">legacy</span> <span class="hljs-string">(pre-10.0.26)</span> <span class="hljs-string">AWS</span> <span class="hljs-string">Portal</span> <span class="hljs-string">File</span> <span class="hljs-string">Transfer...</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO:</span> <span class="hljs-string">Looking</span> <span class="hljs-string">for</span> <span class="hljs-string">legacy</span> <span class="hljs-string">(pre-10.0.26)</span> <span class="hljs-string">File</span> <span class="hljs-string">Transfer</span> <span class="hljs-string">controller</span> <span class="hljs-string">in</span> <span class="hljs-string">/opt/Thinkbox/S3BackedCache/bin/task.py...</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO:</span> <span class="hljs-string">Could</span> <span class="hljs-string">not</span> <span class="hljs-string">find</span> <span class="hljs-string">legacy</span> <span class="hljs-string">(pre-10.0.26)</span> <span class="hljs-string">AWS</span> <span class="hljs-string">Portal</span> <span class="hljs-string">File</span> <span class="hljs-string">Transfer.</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO:</span> <span class="hljs-string">Legacy</span> <span class="hljs-string">(pre-10.0.26)</span> <span class="hljs-string">AWS</span> <span class="hljs-string">Portal</span> <span class="hljs-string">File</span> <span class="hljs-string">Transfer</span> <span class="hljs-string">is</span> <span class="hljs-string">not</span> <span class="hljs-string">installed</span> <span class="hljs-string">on</span> <span class="hljs-string">the</span> <span class="hljs-string">system.</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: INFO:</span> <span class="hljs-string">Executing</span> <span class="hljs-string">global</span> <span class="hljs-string">job</span> <span class="hljs-string">preload</span> <span class="hljs-string">script</span> <span class="hljs-string">'/tmp/deadline/ws232/plugins/643e94b79c6c6405f2284e58/GlobalJobPreLoad.py'</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">***</span> <span class="hljs-string">GlobalJobPreload</span> <span class="hljs-string">start</span> <span class="hljs-string">...</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">>>></span> <span class="hljs-string">Getting</span> <span class="hljs-string">job</span> <span class="hljs-string">...</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">---</span> <span class="hljs-string">Job</span> <span class="hljs-string">type</span> <span class="hljs-bullet">-</span> <span class="hljs-string">render</span> <span class="hljs-number">1</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">---</span> <span class="hljs-string">Job</span> <span class="hljs-string">type</span> <span class="hljs-bullet">-</span> <span class="hljs-string">publish</span> <span class="hljs-number">0</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">---</span> <span class="hljs-string">Job</span> <span class="hljs-string">type</span> <span class="hljs-bullet">-</span> <span class="hljs-string">remote</span> <span class="hljs-number">0</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">>>></span> <span class="hljs-string">Injecting</span> <span class="hljs-string">OpenPype</span> <span class="hljs-string">environments</span> <span class="hljs-string">...</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">>>></span> <span class="hljs-string">Scanning</span> <span class="hljs-string">for</span> <span class="hljs-string">compatible</span> <span class="hljs-string">requested</span> <span class="hljs-string">version</span> <span class="hljs-number">3.15.4</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">>>></span> <span class="hljs-string">Getting</span> <span class="hljs-string">OpenPype</span> <span class="hljs-string">executable</span> <span class="hljs-string">...</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON: --- Looking for OpenPype at:</span> <span class="hljs-string">/prod/softprod/apps/openpype/latest</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:   - found:</span> <span class="hljs-string"><OpenPypeVersion</span> <span class="hljs-number">3.14.7</span><span class="hljs-string">-quad.10></span> <span class="hljs-bullet">-</span> <span class="hljs-string">/prod/softprod/apps/openpype/latest/linux</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span>    <span class="hljs-string">!</span> <span class="hljs-attr">path is not a build:</span> <span class="hljs-string">/prod/softprod/apps/openpype/latest/windows</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON: Looking for OpenPype at:</span> <span class="hljs-string">/prod/softprod/apps/openpype/latest/linux</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:   - found:</span> <span class="hljs-string"><OpenPypeVersion</span> <span class="hljs-number">3.14.7</span><span class="hljs-string">-quad.10></span> <span class="hljs-bullet">-</span> <span class="hljs-string">/prod/softprod/apps/openpype/latest/linux</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">Traceback</span> <span class="hljs-string">(most</span> <span class="hljs-string">recent</span> <span class="hljs-string">call</span> <span class="hljs-string">last):</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span>   <span class="hljs-string">File</span> <span class="hljs-string">"/tmp/deadline/ws232/plugins/643e94b79c6c6405f2284e58/GlobalJobPreLoad.py",</span> <span class="hljs-string">line</span> <span class="hljs-number">309</span><span class="hljs-string">,</span> <span class="hljs-string">in</span> <span class="hljs-string">inject_openpype_environment</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span>     <span class="hljs-string">).format(requested_version))</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON: RuntimeError:</span> <span class="hljs-string">Cannot</span> <span class="hljs-string">find</span> <span class="hljs-string">compatible</span> <span class="hljs-string">version</span> <span class="hljs-string">available</span> <span class="hljs-string">for</span> <span class="hljs-string">version</span> <span class="hljs-number">3.15.4</span> <span class="hljs-string">requested</span> <span class="hljs-string">by</span> <span class="hljs-string">the</span> <span class="hljs-string">job.</span> <span class="hljs-string">Please</span> <span class="hljs-string">add</span> <span class="hljs-string">it</span> <span class="hljs-string">through</span> <span class="hljs-string">plugin</span> <span class="hljs-string">configuration</span> <span class="hljs-string">in</span> <span class="hljs-string">Deadline</span> <span class="hljs-string">or</span> <span class="hljs-string">install</span> <span class="hljs-string">it</span> <span class="hljs-string">to</span> <span class="hljs-string">configured</span> <span class="hljs-string">directory.</span>

<span class="hljs-attr">2023-04-18 15:02:41:  0: PYTHON:</span> <span class="hljs-string">!!!</span> <span class="hljs-string">Injection</span> <span class="hljs-string">failed.</span>

<span class="hljs-attr">2023-04-18 15:02:42:  0:</span> <span class="hljs-string">'/users_roaming/mgutmann/Thinkbox/Deadline10/pythonAPIs/8V8myYiuCTeqVADSSX273A=='</span> <span class="hljs-string">already</span> <span class="hljs-string">exists.</span> <span class="hljs-string">Skipping</span> <span class="hljs-string">extraction</span> <span class="hljs-string">of</span> <span class="hljs-string">PythonSync.</span>

<span class="hljs-attr">2023-04-18 15:02:43:  0:</span> <span class="hljs-string">Done</span> <span class="hljs-string">executing</span> <span class="hljs-string">plugin</span> <span class="hljs-string">command</span> <span class="hljs-string">of</span> <span class="hljs-string">type</span> <span class="hljs-string">'Start Job'</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-string">Details</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-attr">Date:</span> <span class="hljs-number">04</span><span class="hljs-string">/18/2023</span> <span class="hljs-number">15</span><span class="hljs-string">:02:46</span>

<span class="hljs-attr">Frames:</span> <span class="hljs-number">101</span>

<span class="hljs-attr">Elapsed Time:</span> <span class="hljs-number">00</span><span class="hljs-string">:00:00:09</span>

<span class="hljs-attr">Job Submit Date:</span> <span class="hljs-number">04</span><span class="hljs-string">/18/2023</span> <span class="hljs-number">15</span><span class="hljs-string">:01:43</span>

<span class="hljs-attr">Job User:</span> <span class="hljs-string">mgutmann</span>

<span class="hljs-attr">Average RAM Usage:</span> <span class="hljs-number">70873022464</span> <span class="hljs-string">(53%)</span>

<span class="hljs-attr">Peak RAM Usage:</span> <span class="hljs-number">70885396480</span> <span class="hljs-string">(53%)</span>

<span class="hljs-attr">Average CPU Usage:</span> <span class="hljs-number">97</span><span class="hljs-string">%</span>

<span class="hljs-attr">Peak CPU Usage:</span> <span class="hljs-number">99</span><span class="hljs-string">%</span>

<span class="hljs-string">Used</span> <span class="hljs-string">CPU</span> <span class="hljs-string">Clocks</span> <span class="hljs-string">(x10^6</span> <span class="hljs-string">cycles):</span> <span class="hljs-number">120296</span>

<span class="hljs-string">Total</span> <span class="hljs-string">CPU</span> <span class="hljs-string">Clocks</span> <span class="hljs-string">(x10^6</span> <span class="hljs-string">cycles):</span> <span class="hljs-number">124016</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-string">Worker</span> <span class="hljs-string">Information</span>

<span class="hljs-string">=======================================================</span>

<span class="hljs-attr">Worker Name:</span> <span class="hljs-string">ws232</span>

<span class="hljs-attr">Version:</span> <span class="hljs-string">v10.1.23.6</span> <span class="hljs-string">Release</span> <span class="hljs-string">(773a6289d)</span>

<span class="hljs-attr">Operating System:</span> <span class="hljs-string">Linux</span>

<span class="hljs-attr">Machine User:</span> <span class="hljs-string">root</span>

<span class="hljs-attr">IP Address:</span> <span class="hljs-number">10.10.9.234</span>

<span class="hljs-attr">MAC Address:</span> <span class="hljs-string">B0:7B:25:28:82:C1</span>

<span class="hljs-attr">CPU Architecture:</span> <span class="hljs-string">x86_64</span>

<span class="hljs-attr">CPUs:</span> <span class="hljs-number">24</span>

<span class="hljs-attr">CPU Usage:</span> <span class="hljs-number">96</span><span class="hljs-string">%</span>

<span class="hljs-attr">Memory Usage:</span> <span class="hljs-number">66.0</span> <span class="hljs-string">GB</span> <span class="hljs-string">/</span> <span class="hljs-number">125.5</span> <span class="hljs-string">GB</span> <span class="hljs-string">(52%)</span>

<span class="hljs-attr">Free Disk Space:</span> <span class="hljs-number">293.270</span> <span class="hljs-string">GB</span>

<span class="hljs-attr">Video Card:</span> <span class="hljs-string">NVIDIA</span> <span class="hljs-string">Corporation</span> <span class="hljs-string">TU104GL</span> [<span class="hljs-string">Quadro</span> <span class="hljs-string">RTX</span> <span class="hljs-number">5000</span>] <span class="hljs-string">(rev</span> <span class="hljs-string">a1)</span>

## Softwares concerned

Maya, Fix

`/labels ~"Company::FIX" ~"Soft::Maya"`
![6f196c4d85](https://my-gitlab-bucket.s3.amazonaws.com/602095763/4901689cb12b3220f37d824f6136422ddf030cf4ad8e05fd1c48933315d028d1/6f196c4d85.png)

**Comment by louparis** [comment]
https://github.com/ynput/OpenPype/pull/4484
