### ISSUE TITLE
Can't add Blender 3.1.4

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#398]
In GitLab by @support-bot on Apr 24, 2023, 13:52

> From Kevin Zarshenas

## Problem

I tried to add Blender 3.1.4 into OpenPype applications but it does not work.

## How get error

- I duplicated the blender 3-0-1
- I change the name with 3-1-4, the label with 3.1.4

![image](https://user-images.githubusercontent.com/70959083/236422794-651eaa7b-6182-4e77-94dd-92faf8420ec8.png)

- I set the correct blender path file (app folder is correct, i test to launch it with terminal)
- I add BLENDER\_VERSION env var
- I add blander 3.1.4 to TEST\_OP2\_PUB
- Then I have the error message :

![image](https://user-images.githubusercontent.com/70959083/236422812-3c7fc3e2-4409-4e6c-8168-b525baecd98c.png)

## Log

```
Missing definition of application Blender/3-1-4
```

## Softwares concerned

Blender, Fix

**Comment by ccaillot** [comment]
@ClementHector Fonctionne après avoir éxécuté le docker 'ftrack-sync-fix' en local avec la dernière update d'openpype (3.15.8-nightly.3), le docker situé sur 'dockersquad' quand a lui ne fonctionne pas

**Comment by ccaillot** [comment]
Cet erreur a été résolue après avoir mis a jour le service [docker](https://github.com/quadproduction/openpype-module-docker)

**Comment by ClementHector** [comment]
J'ai rencontré des problèmes avec la synchronisation de Kitsu en raison de l'incompatibilité de l'API Gazu dans OpenPype. Pour résoudre ce problème, j'ai effectué la mise à jour de Gazu avec poetry vers 0.9.3 dans dans le Docker et j'ai changé l'image de CentOS à Debian pour obtenir la version 1.1.1 de la bibliothèque OpenSSL, car la version 1.0.2 de CentOS est devenue incompatible.
