### ISSUE TITLE
Hiero: "OCIO config" setting doesn't work

### ISSUE THREAD

**Issue by friquette** [quadproduction/OpenPype#415]
The "OCIO config" OP setting doesn't work

**Comment by ccaillot** [comment]
Workflow between Nuke and Nuke Hiero are now the same, none issue detected with bad colorspace. 
Sounds good on my side. Need to be confirmed by people from editing or any people who are comfortable with OCIO in Nuke' environment.

![Image](https://github.com/quadproduction/OpenPype/assets/134272390/3a327a4d-188a-49f2-8e29-6d12d9e23f16)

**Comment by ccaillot** [comment]
Settings which has been modified appear in the 'TEST_OP2_PUB_23_7' project and need to be pushed on the 'Default' Project once it will be checked and approved.

**Comment by ClementHector** [comment]
Value apply in Default ans Silkies
