### ISSUE TITLE
Enhancement: animation family loaded as standin (ABC) don't have correct fps and "use file sequence" ticked

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

animation family loaded as standin (ABC) should have correct fps and "use file sequence" ticked as they are animated entites

![image](https://github.com/quadproduction/OpenPype/assets/59604835/d11a28fd-5f22-46d0-a010-b800c50aba67)

### How would you imagine the implementation of the feature?

when animation family is loaded as standing we should get the fps of the project and we should 
setAttr "_001_0010_02_:feadingPump_rigMain_01__standinShape.useFrameExtension" 1;

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

### Additional context:

can be tested on TEST_OP2_PUB_23_7 by loading in the shot 001_0010 the animation published there as a standing (ABC)

**Comment by FadyFS** [comment]
PR = https://github.com/ynput/OpenPype/pull/5110

**Comment by OlivierOsotimehin** [comment]
I have Seen the ticket on pypeclub side and WE should get dynamicaly the FPS of the project that Can change between 24/25/30 
That settings is stored in database (openpype and ftrack)

**Comment by OlivierOsotimehin** [comment]
I have just read thé last update on pypeclub side, it good now 👍

**Comment by ClementHector** [comment]
There is still a correction to be made for the line length.

**Comment by OlivierOsotimehin** [comment]
hello, on OP 3.15.12-quad0.1

the "use file sequence " is now ticked 
but the fps is not set to the correct number (test on TEST_OP2_PUB_23_7)

**Comment by OlivierOsotimehin** [comment]
Sorry i have to restest 
but the shot 001_0010 has been override in the OP project manager to be at 30 fps 

![Image](https://github.com/quadproduction/OpenPype/assets/59604835/c2d5f405-1382-43c9-a059-56c562e0d394)

when i try it in the shot 001_0020  i have the correct fps of the project 
so it is working ... sorry again

**Comment by FadyFS** [comment]
okay thank you !
