### ISSUE TITLE
Bug: OpenPype Error "Kitsu Entities"

### ISSUE THREAD

**Issue by Alice51000** [quadproduction/OpenPype#467]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Not yet

### Version

3.14.7

### What platform you are running OpenPype on?

Windows

### Current Behavior:

Hello

On a rencontré un problème lors du publish d'un shot sur kitsu sur le projet Wizard With a Gun.
Nous avons un message d'erreur concernant les data du shot semble-t-il mais je crois que toutes les infos sont correctes dans kitsu (fps, ratio, resolution) du coup je ne comprends d'où ça viendrait.
![image](https://github.com/quadproduction/OpenPype/assets/134387402/34fad5a5-64b9-4caa-84b1-3264e9b620ab)
On a rencontré ça sur le sh110

### What type of bug is it ?

None

### Which project / workfile / asset / ...

Wizard With a Gun III / ANIMATION / SHOT110

### Steps To Reproduce:

1. Je lance la task Tie Down via OpenPype
2. Le TVPaint s'ouvre sans soucis apparent
3. Le publish m'indique une erreur à la ligne Kitsu Entities dans le menu COLLECT
4. Le publish ne se fait pas
5. merci pour votre lecture
6. bisous

**Comment by Alice51000** [comment]
Hello @FadyFS, what do you mean by asset ?

**Comment by FadyFS** [comment]
Hi, I mean the prject you did the test on. The one above pointed by an arrow on my screenshot.
It is the same as the one you tried the publish on (Wizard With a Gun III / ANIMATION / SHOT110) ?

**Comment by Alice51000** [comment]
Yes that's it. The artist tried, it failed. And I tried myself, it failed too. On your side it's working ?

**Comment by FadyFS** [comment]
Apparently, yes. Do you have time to show me in real life ?

**Comment by Alice51000** [comment]
Yes, how do you want to proceed ?

**Comment by Alice51000** [comment]
Ok @FadyFS I can't explain how, but it worked... I just publish the shot 😱

**Comment by FadyFS** [comment]
no way amazing, let me know if anything happens !
