### ISSUE TITLE
Enhancement: Lentil for Arnold (MtoA)

### ISSUE THREAD

**Issue by breuerdesign** [quadproduction/OpenPype#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Installation du plugin Lentil pour Maya, permettant d'accélerer le calcul et le controle du flou + Bokeh des images. 
(30x plus rapide que la DoF d'Arnold environ)
Website : https://www.lentil.xyz/
GitHub : https://github.com/zpelgrims/lentil

### How would you imagine the implementation of the feature?

-

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by ClementHector** [comment]
@fixstudio-it Pouvez vous nous dire ou est installé le plugin, merci.

**Comment by breuerdesign** [comment]
Le plug-in n'est pas installé, il faut le compiler il me semble. Nicolas Biardeau etait sur le sujet, il peut surement t'en dire plus. Il doit y avoir les indications sur GitHub. Merci !

**Comment by ClementHector** [comment]
C'est quoi ton erreur?
