### ISSUE TITLE
Maya Set Frame range error

### ISSUE THREAD

**Issue by SherineKB** [quadproduction/OpenPype#482]
On version 3.15.12-quad.0.1 :
```
# openpype.hosts.maya.api.lib : Setting scene FPS to: 'pal'
# Error: NameError: file /users_roaming/skacmazbelhaine/openpype/OpenPype/openpype/hosts/maya/api/lib.py line 2277: name 'animation_start' is not defined
```
when i try to set framerange with openpype.
To test, set your openpype on branch 3.15.12-quad.0.1

**Comment by ClementHector** [comment]
I solve this issue by adding avalon auto sync in the ftack project:


![Image](https://github.com/quadproduction/OpenPype/assets/7068597/e7987f99-4a6f-4f47-87d1-3f282594e056)
