### ISSUE TITLE
Enhancement: we would like to add custom script to the Fix studio menu

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

We would like to add 2 rig script package to the FixStudio menu under the rig section : 

Advanced skeleton and UltimateAdjustableCarRig

You can find them there 
/prod/prod2/Projets/RESSOURCES/_graphistes/oso/rig/AdvancedSkeleton
/prod/prod2/Projets/RESSOURCES/_graphistes/oso/rig/UltimateAdjustableCarRig-Lite

### How would you imagine the implementation of the feature?

Store the script in a safe place (that can be easily updatable)
add an entry to the fixstudio menu to be able to launch them

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by SherineKB** [comment]
To test it, go on Fix|Studio and check if the Advanced Skeleton and Ultimate Adjustable Car Rig buttons are working. 


![Image](https://github.com/quadproduction/OpenPype/assets/130908605/b61e6a44-2fed-4c84-af1c-2c514e574232)
