### ISSUE TITLE
Bug: Open Pype 3.15.11 - Publishing is not working on Photoshop

### ISSUE THREAD

**Issue by rebecahayem** [quadproduction/OpenPype#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

 Publishing is not working on Photoshop. Error : 

![image](https://github.com/quadproduction/OpenPype/assets/132449981/594797e8-eb42-43ec-981c-77c8b8ee56d9)

### Version

3.15.11

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

Publish on Photoshop on Windows. 

Computer WS099

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by Alice51000** [comment]
Hello,

Photoshop version you mean ?

**Comment by fixstudio-it** [comment]
Updates works with last version of photoshop said Rebeca : Version de juin 2023 (version 24.6)

Can deploy to all wizz workstations
