### ISSUE TITLE
Bug: animation instance doesnt take into account the handle when abc is generated

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#518]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Yes I have

### Author of the bug

olivier.osotimehin@fixstudio.com

### Version

3.15.12-quad.4.1

### What platform you are running OpenPype on?

Linux / Centos

### Current Behavior:

Bug: animation instance doesn't take into account the handle when abc is generated and "Include handle" is set to on in the settings 

![image](https://github.com/quadproduction/OpenPype/assets/59604835/f874eff4-d003-402f-86d9-6a1511736a4e)

### Expected Behavior:

Exported animation instances (abc or whatever) should includes the handles when "Includes handles" is set to on on the settings

### What type of bug is it ?

Happens everytime with different configurations

### Which project / workfile / asset / ...

TEST_OP2_PUB_23_7 / shots / 101 / 101_0010 animation 

### Steps To Reproduce:

Publish a shot with animation instances set to publish abc and like at the frame range of the animation exported

**Comment by ccaillot** [comment]
Tested with this asset (/prod/project/TEST_OP2_PUB_23_7/5_FILM/Shots/001/001_0010/publish/animation/can_animation_rigBasic_01_/v004/001_0010_can_animation_rigBasic_01__v004.abc), as you can see, the animation during the handle has been well exported.
