### ISSUE TITLE
Bug: No Review on Kitsu after Photoshop Publish

### ISSUE THREAD

**Issue by rebecahayem** [quadproduction/OpenPype#521]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Yes I have

### Author of the bug

Rebeca Hayem

### Version

3.15.11

### What platform you are running OpenPype on?

Windows

### Current Behavior:

When I publish BG assets with Photoshop everything works fine except nothing is uploaded on Kitsu. 

### Expected Behavior:

The jpg on the review folder should also be uploaded on Kitsu:

L:\2023\WIZARDS_WITH_GUNS_3_23_17\Assets\BG\BG01_SH110_C\publish\review\review\v001

### What type of bug is it ?

None

### Which project / workfile / asset / ...

WIZARDS_WITH_GUNS_3_23_17

### Steps To Reproduce:

Open Photoshop and Publish an Asset

### Additional context:

No logs or errors were pointed out by the pyblish tool

**Comment by ccaillot** [comment]
I've replaced this parameter "Add Review to FTrack" by "Add Review to Kitsu" in "Project settings > photoshop > Publish > Extract Review" in WIZARDS_WITH_GUNS_3, Can you tell me if this change something on your side ?

**Comment by hfarre** [comment]
I tested on the PROJECT_ZERO_KITSU_OP_23_21, asset H_BG_02, task Painting, Photoshop 2023, with the settings correctly set up
But after a publish with the review activated, no review on kitsu was made and the step in the publish window is always skipped

**Comment by ccaillot** [comment]
Can try again by selecting the image well, it is important for pyblish:


![Image](https://github.com/quadproduction/OpenPype/assets/134272390/bc596f32-2e3b-4333-926a-b382df6856d7)



![Image](https://github.com/quadproduction/OpenPype/assets/134272390/c2415bc0-0a40-4a46-9669-ba8ba54adf05)

**Comment by hfarre** [comment]
We already found this solution, but what we want to achieve is to create a review on kitsu, without publishing an image, just a preview via kitsu to have a review on the work

Here is the solution found without using the review option:

![Image](https://github.com/quadproduction/OpenPype/assets/139864808/849dc310-2c24-4b02-9a62-0062b1ae10c5)


Maybe it doesn't make sense for openpype, and the use of the image publishing is necessary ?

**Comment by ccaillot** [comment]
I've made a quick fix on this [branch](https://github.com/quadproduction/OpenPype/tree/bugfix/521-bug-no-review-on-kitsu-after-photoshop-publish), can you test it and tell me it this solution fit your needs ? Thanks

In order to test, you must only select tthe review and write a comment, this will be upload in Kitsu

**Comment by hfarre** [comment]
Hello

This fix work wonderfully ! With only the review activated, it goes on Kitsu with a thumbnail and all the associated picture file created

I just maybe found a tiny bug

When you want to publish the asset this way:
![image](https://github.com/quadproduction/OpenPype/assets/139864808/7af41ed3-5ea4-4687-b9a4-d5463199aedb)

Using the Review option, but not in the imageMain, it will create the review, and the publish, but not the publish thumbnail:
![image](https://github.com/quadproduction/OpenPype/assets/139864808/94174440-cee2-4e8b-be48-52e45ad3598e)
This is the review created, no problem

![image](https://github.com/quadproduction/OpenPype/assets/139864808/95058234-a269-4770-a207-77421d44ad05)
But in the loader we don't have any thumbnail for the published asset

Thanks again for the good way it is taking :D

**Comment by ccaillot** [comment]
After conducting some thorough investigations, it has come to my attention that the fix I previously provided on the custom Git branch may pose a significant risk and, more importantly, it deviates from the proper usage guidelines of Openpype.
To rectify this situation and ensure clarity in the usage of the 'Reviews' options, I recommend deactivating one of them.

Specifically, this adjustment will achieve the following:

Image export functionality will capture and export the content currently displayed in the Photoshop viewer.

Workfill export will manage and export the entire scene accordingly.

Here is an illustrative link to the associated image: 

![Image](https://github.com/quadproduction/OpenPype/assets/134272390/657056e2-4601-43d0-907e-c622b0781aa2)

**Comment by hfarre** [comment]
Thanks for the update ! :) 

For photoshop I think we can work this way, the result will end up the same as a review.
