### ISSUE TITLE
Bug:No imported reviews on kitsu when publishing on TV Paint

### ISSUE THREAD

**Issue by hfarre** [quadproduction/OpenPype#540]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Yes I have

### Author of the bug

Hadrien FARRE 

### Version

3.15.12-quad.4.1

### What platform you are running OpenPype on?

Windows

### Current Behavior:

On the TestKitsuOpenPype/SQ01_SH102/Rough_Anim project

When you want to simply publish a review like this
![image](https://github.com/quadproduction/OpenPype/assets/139864808/debf36ca-547c-424c-b93e-99e7c11daa85)

The files are well created but nothing happens on kitsu
This probably has something to do with families or instance tags in Extract Sequence. This is only a lead and requires digging.

Because if we check renderMain to publish, then reviews and comments appear on kitsu
Car si on coche renderMain à publish, alors des review et commentaires apparaissent sur kitsu
![image](https://github.com/quadproduction/OpenPype/assets/139864808/13fbbef7-0184-4151-8f22-ce16e975c7ae)

### Expected Behavior:

Having the reviews upload to kitsu

### What type of bug is it ?

Happens everytime with different configurations

### Which project / workfile / asset / ...

TestKitsuOpenPype/SQ01_SH102/Rough_Anim

### Steps To Reproduce:

1. Open a rough anim scene of the project with tv paint
2. publish it without changing any settings

**Comment by friquette** [comment]
Doublon with this issue https://github.com/quadproduction/OpenPype/issues/510
