### ISSUE TITLE
Enhancement: Add new App Watch Manager

### ISSUE THREAD

**Issue by abouchafra** [quadproduction/OpenPype#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Add a new app

### How would you imagine the implementation of the feature?

The app will be in project that needs this application

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by FadyFS** [comment]
follow this tutorial  for testing : 
https://tropical-heat-f1f.notion.site/Tuto-415bc5ca24f4409094eed15ec7116914
