### ISSUE TITLE
Extraction abc camera failed

### ISSUE THREAD

**Issue by ClementHector** [quadproduction/OpenPype#558]
Alembic camera extration fail with error:
```
Traceback (most recent call last):
  File "/users_roaming/chector/Documents/src/OpenPype/.venv/lib/python3.9/site-packages/pyblish/plugin.py", line 522, in __explicit_process
    runner(*args)
  File "/users_roaming/chector/Documents/src/OpenPype/openpype/hosts/maya/plugins/publish/extract_camera_alembic.py", line 104, in process
  File "/users_roaming/chector/Documents/src/OpenPype/openpype/hosts/maya/plugins/publish/extract_camera_alembic.py", line 2, in AbcExport
RuntimeError: |root and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have parenting relationships
|root and |root|grp_cam|camera_camerarigMain_01:asset|camera_camerarigMain_01:root|camera_camerarigMain_01:grp_camera|camera_camerarigMain_01:camera have an ancestor relationship.

```

**Comment by louparis** [comment]
Can't reproduce this bug. Can you check on your side @MarcGutmann @OlivierOsotimehin Thanks

**Comment by MarcGutmann** [comment]
Help us a little !
We have been working for several months on Silkies, the only project on OpenPype. This ticket has existed for over a month and we are stuck on the ABC export of the camera.
Open an animation scene from the Silkies project (for example 002_0010) then publish the camera.

**Comment by MarcGutmann** [comment]
Help us a little !
We have been working for several months on Silkies, the only project on OpenPype. This ticket created by a dev has existed for over a month and we are stuck on the ABC export of the camera.
Open an animation scene from the Silkies project (for example 002_0010) then publish the camera.

**Comment by MarcGutmann** [comment]
It doesn't wrok
It published the maya camera but not the alembic camera

![Image](https://github.com/quadproduction/OpenPype/assets/135047527/ae4efc65-39fe-4372-a128-8e783edceee1)

**Comment by MarcGutmann** [comment]
Tested on plan 002_0010 of the silkies project

**Comment by OlivierOsotimehin** [comment]
Nouvelle version 3.15.12-quad.3.8
