### ISSUE TITLE
Nuke Bug: Nothing works in the in the Fix|Studio menu 

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#564]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Not yet

### Author of the bug

olivier.osotimehin@fixstudio.com

### Version

3.15.12-quad.4.1

### What platform you are running OpenPype on?

Linux / Centos

### Current Behavior:

When we try to use the tool in the Fix|Studio menu nothing works. 

### Expected Behavior:

we can use the tools in the menu

### What type of bug is it ?

Happens everytime with different configurations

### Which project / workfile / asset / ...

TEST_OP2_PUB_23_7 / 001_0010 / compo

### Steps To Reproduce:

launch nuke and try to use the different tools in the menu

**Comment by OlivierOsotimehin** [comment]
![image](https://github.com/quadproduction/OpenPype/assets/59604835/ca8ca455-2aac-4dbd-b290-ba4a7d7da520)

**Comment by ThibaultMarteg** [comment]
Thanks !
can you add to this feature the shortcut "ALT"+"d" for the tools----> "copylink" please?

**Comment by friquette** [comment]
> Thanks ! can you add to this feature the shortcut "ALT"+"d" for the tools----> "copylink" please?

It seems that Alt+D is already taken in Nuke. You can either remove the existing shortcut, or find another one to set in OP

**Comment by ThibaultMarteg** [comment]
I'm in OpenPype , project TERMINAL_H, and nothing happen when I use Alt+D. 
And we used to use this shortcut in Shotgrid's Nuke, with no problem, for the last few years. Is it a new feature that I can't see?

**Comment by friquette** [comment]
> I'm in OpenPype , project TERMINAL_H, and nothing happen when I use Alt+D. And we used to use this shortcut in Shotgrid's Nuke, with no problem, for the last few years. Is it a new feature that I can't see?

There's a feature called "Force Dope Sheet On/Off" in the nodes (the last one):
![image](https://github.com/quadproduction/OpenPype/assets/51854004/e3b19155-86a2-4e51-9a3a-fb4dab3cd9a7)

**Comment by ThibaultMarteg** [comment]
Ah ok
But it seems we never use this feature, and we use to click Alt+D to duplicate node and connections in Shotgrid. Is it possible to the same in OpenPype?
Don't hesitate to join me directly by chat or by phone for more explanations

**Comment by louparis** [comment]
The sortcut now works. We added it to TERMINAL_H & SILKIES, and default. 
Once you've tested it, you can close this ticket.

**Comment by ThibaultMarteg** [comment]
Ok it works thanks
I close the ticket (as usual)
