### ISSUE TITLE
Nuke Bug: The Fix|Gizmo side Menu does not work and it's missing it's icon

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#566]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Yes I have

### Author of the bug

olivier.osotimehin@fixstudio.com

### Version

3.15.12-quad.4.1

### What platform you are running OpenPype on?

Linux / Centos

### Current Behavior:

The Fix|Gizmo is missing it's icon : 
![image](https://github.com/quadproduction/OpenPype/assets/59604835/6b12f600-7403-431e-a75d-4180c489ee4d)

None of the tool inside the Fix|Gizmo work : we have a unknown command error

![image](https://github.com/quadproduction/OpenPype/assets/59604835/1899c6a4-b0c1-4376-a3cf-fe77c1c04efb)

### What type of bug is it ?

Happens everytime with different configurations

### Which project / workfile / asset / ...

TEST_OP2_PUB_23_7 / 001_0020 / light

### Steps To Reproduce:

click in the menu

**Comment by ThibaultMarteg** [comment]
Thanks!
