### ISSUE TITLE
Nuke Enhancement: Fix|Gizmo menu is missing a lot of gizmo that are present in the shotgun pipeline

### ISSUE THREAD

**Issue by OlivierOsotimehin** [quadproduction/OpenPype#567]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

We should keep the gizmo already in present and add all that is in the Fixstudio menu in the shotgun pipeline : 

![image](https://github.com/quadproduction/OpenPype/assets/59604835/314bdfe6-8276-4f7f-9282-cde41428be40)

### How would you imagine the implementation of the feature?

add back the gizmo missing in the shotgun pipeline

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

**Comment by SherineKB** [comment]
To test it : 
Go to the "openpype_software_plugins" repository and into "/host/nuke/gizmos/".
You have all the guizmos files.

Go in Nuke, Fix sidebar menu, and compare the repository content with the Fix menu content and see if all the guizmos are present.

![Image](https://github.com/quadproduction/OpenPype/assets/130908605/25c08c04-eb9f-4f41-89e4-630506cb2979)


**warning** : before testing it, this ticket needs to work : https://github.com/quadproduction/OpenPype/issues/566
