### ISSUE TITLE
Bug: autorig de props doesn't work

### ISSUE THREAD

**Issue by louparis** [quadproduction/OpenPype#571]
### Before posting a new ticket, have you looked through the documentation to find an answer?

Yes I have

### Have you looked through the existing tickets to find any related issues ?

Yes I have

### Version

3.15.12-quad.4.1

### What platform you are running OpenPype on?

Linux / Centos

### Current Behavior:

```# Traceback (most recent call last):#   File "/users_roaming/mgutmann/.local/share/openpype/3.15/openpype-v3.15.12-quad.3.3/openpype/vendor/python/common/scriptsmenu/action.py", line 135, in run_command#     exec(self.process_command())#   File "<string>", line 1, in <module># ImportError: cannot import name 'rig_props' from 'host.maya.python' (unknown location)```

### What type of bug is it ?

None

### Which project / workfile / asset / ...

--

### Steps To Reproduce:

--

**Comment by MarcGutmann** [comment]
To reproduce the bug, click on FixStudio Menu, Rig > Autorig Props

**Comment by friquette** [comment]
PR => https://github.com/quadproduction/openpype-software-plugins/pull/3
